spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      httpclient:
        connect-timeout: 5000
        response-timeout: 10000
      default-filters:
        - TokenRelay
        - PreserveHostHeader
      routes:
        - id: sales-service
          uri: lb://sales-service
          predicates:
            - Path=/sales-service/**
          filters:
            - StripPrefix=1
            - TokenRelay
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/catalog-service/**
          filters:
            - StripPrefix=1
            - TokenRelay
        - id: payments-service
          uri: lb://payments-service
          predicates:
            - Path=/payments-service/**
          filters:
            - StripPrefix=1
            - TokenRelay
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1
            - TokenRelay

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG

# Configuraciones JWT
security:
  jwt:
    private:
      key: ${PRIVATE_KEY}
    user:
      generation: ${USER_GENERATOR}